<?xml version="1.0" encoding="utf-8"?><Database Name="SHOPBANHANG" Class="MyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietGioHang" Member="ChiTietGioHangs">
    <Type Name="ChiTietGioHang">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGioHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="SanPham_ChiTietGioHang" Member="SanPham" ThisKey="id" OtherKey="id" Type="SanPham" IsForeignKey="true" />
      <Association Name="GioHang_ChiTietGioHang" Member="GioHang" ThisKey="MaGioHang" OtherKey="MaGioHang" Type="GioHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tensp" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_ChiTietGioHang" Member="ChiTietGioHangs" ThisKey="id" OtherKey="id" Type="ChiTietGioHang" />
    </Type>
  </Table>
  <Table Name="dbo.GioHang" Member="GioHangs">
    <Type Name="GioHang">
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MaGioHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GioHang_ChiTietGioHang" Member="ChiTietGioHangs" ThisKey="MaGioHang" OtherKey="MaGioHang" Type="ChiTietGioHang" />
    </Type>
  </Table>
</Database>